### ISSUE TITLE
ipfs add example failure 

### ISSUE THREAD

**Issue by danoctavian** [ipfs/node-ipfs-api#36]
for example:

https://github.com/ipfs/node-ipfs-api/blob/master/examples/add.js

i am getting this error trace:

path.js:439
      throw new TypeError('Arguments to path.resolve must be strings');
      ^
TypeError: Arguments to path.resolve must be strings
    at Object.posix.resolve (path.js:439:13)
    at Object.posix.relative (path.js:505:16)
    at addFile (/home/dan/node_modules/ipfs-api/multipartdir.js:56:23)
    at MultipartDir (/home/dan/node_modules/ipfs-api/multipartdir.js:14:5)
    at getFileStream (/home/dan/node_modules/ipfs-api/index.js:151:12)
    at send (/home/dan/node_modules/ipfs-api/index.js:47:16)
    at Object.add (/home/dan/node_modules/ipfs-api/index.js:170:14)
    at Object.<anonymous> (/home/dan/repos/haskell-ipfs-api/playground/contact_ipfs.js:15:6)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by jbenet** [comment]
maybe similar to #34 ?

**Comment by danoctavian** [comment]
perhaps.

i was trying to write a ipfs rest API implementation for haskell

https://github.com/danoctavian/haskell-ipfs-api

and i got stuck on the add command because i don't understand the http request requirements. i was using this node implementation as a reference.

Is there a better reference implementation at this point? or i'm better off  just reading go-ipfs code and see what it expects?

**Comment by jbenet** [comment]
@danoctavian i think inspecting the HTTP traffic of go-ipfs will be the best way. ngrok2 does this really nicely.

**Comment by danoctavian** [comment]
@jbenet cool, ty

**Comment by krl** [comment]
Add is not behaving properly across node and browsers, i'm going to write some tests to make sure we get this right in the coming days.

**Comment by diasdavid** [comment]
Is this still a problem? @krl ?

**Comment by krl** [comment]
nope, seems to work again
